---
title: "Lab 3"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

## Regression Tree
```{r libraries}
library(rpart)
library(rpart.plot)
```

```{r}
data("msleep")
str(msleep)
str(data)
```


```{r}
msleepdf1=msleep[,c(3,6,10,11)]
str(msleepdf1)
head(msleepdf1)
```

```{r}
sleepModel_1=rpart(sleep_total~.,data = msleepdf1,method = "anova")
sleepModel_1
```


```{r}
rpart.plot(sleepModel_1,type=3,fallen.leaves = T)
rpart.plot(sleepModel_1,type=3,digits = 3,fallen.leaves = T)
rpart.plot(sleepModel_1,type=3,digits = 4,fallen.leaves = T)
```

## Classification Tree

```{r}
require(C50)
data("iris")
head(iris)
str(iris)
table(iris$Species)

set.seed(9850)
grn=runif(nrow(iris))
hist(grn)
irisrand=iris[order(grn),]
str(irisrand)
classmodel1=C5.0(irisrand[1:100,-5],irisrand[1:100,5])
classmodel1
summary(classmodel1)
```
```{r}
prediction1=predict(classmodel1,irisrand[101:150,-5])
prediction1
table(irisrand[101:150,5],prediction1)
```


```{r}
plot(classmodel1)
```

